language: cpp
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libssl1.1
      - cmake-data
      - python3-pip

cache:
  directories:
  - Debug/googletest
  - Debug/log4cplus
  - yaml-cpp-yaml-cpp-0.6.2/build

env:
- MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
- eval ${MATRIX_EVAL}

install:
- pip3 install robotframework
- travis_retry wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz
- tar zxvf yaml-cpp-0.6.2.tar.gz
- cd yaml-cpp-yaml-cpp-0.6.2
- if [ ! -d build ]; then mkdir build; fi &&
  cd build &&
  cmake .. &&
  cmake --build . &&
  sudo env "PATH=$PATH" cmake --build . --target install

script:
- cd ${TRAVIS_BUILD_DIR}
- pushd log4cplus
- autoreconf -f
- popd
- if [ ! -d build ]; then mkdir build; fi &&
  cd Debug &&
  cmake .. &&
  cmake --build . &&
  ctest --output-on-failure
